### ISSUE TITLE
Homework Deadline

### ISSUE THREAD

**Issue by ktpss95112** [amjltc295/PythonHomework#101]
![image](https://user-images.githubusercontent.com/20783464/49323624-43038a00-f559-11e8-9de3-efd53fc45c86.png)
In the slides on ceiba, it says the deadline is 12/2(Monday). 
First, 12/2 is Sunday. Is that a typo of "12/3"?
Second, I have confirmed with my classmates that we all heard the TA said the deadline should be 12/10 during the course this week(11/26). 
That's confusing. What should be the correct deadline? Furthermore, if the origin deadline is 12/2 or 12/3, can it be put off to 12/10 since it is the date addressed during the course?

**Comment by MrBear2000** [comment]
I also heard that the deadline is 12/10.

**Comment by amjltc295** [comment]
The deadline is 12/10. I will send a mail later.

**Comment by ktpss95112** [comment]
Thanks.
