### ISSUE TITLE
Why my "Travis CI - Pull Request" failed?

### ISSUE THREAD

**Issue by meow87wang** [amjltc295/PythonHomework#121]
As the title, I would like to know why my "Travis CI - Pull Request" failed.
Thanks.

**Comment by meow87wang** [comment]
@amjltc295

**Comment by amjltc295** [comment]
You could see your build log [here](https://travis-ci.com/amjltc295/PythonHomework/builds/93676463)

**Comment by amjltc295** [comment]
In the PR, click 'details' -> 'The build'

**Comment by amjltc295** [comment]
Your code has a syntax error. DId you test it locally?
