### ISSUE TITLE
I can't find my miniconda.

### ISSUE THREAD

**Issue by YuCheng701248202077** [amjltc295/PythonHomework#128]
I have installed both python3.7 and miniconda for sure , but the terminal just kept responding: " command not found: conda" Even after typing "export PATH=~/miniconda3/bin:$PATH" , the terminal just didn't work.
TA have succeeded in finding  my existing python3.7 in 11/26 in my laptop, so I wonder how can I follow the same path?  

thanks for answering!

**Comment by YuCheng701248202077** [comment]
@amjltc295

**Comment by amjltc295** [comment]
Where did you install your Miniconda? You need to make sure your Miniconda binary path is the same as the one in `export PATH=~/miniconda3/bin:$PATH`.
By the way, you should have asked this question earlier.
