### ISSUE TITLE
Question for Task 8

### ISSUE THREAD

**Issue by sophiameerkat** [amjltc295/PythonHomework#130]
I have pulled the latest version and used autograder to test my code. For task 8, I get 4 points but still have the error message "cannot open resource". How can I fix the problem?

**Comment by s950449** [comment]
Could you paste your log here?

**Comment by amjltc295** [comment]
The error is caught and handled in `util.py`. As long as you get the points, you will be fine. If you want to fix the problem, just install corresponding font.

**Comment by amjltc295** [comment]
I also changed the error message to warning in the latest code

**Comment by sophiameerkat** [comment]
Thanks.
