### ISSUE TITLE
How is my commit message  not linked to my  profile?

### ISSUE THREAD

**Issue by YuCheng701248202077** [amjltc295/PythonHomework#169]
As titled, TA reminded me that my commit message  was not linked to my file correctly,
but I'm not pretty sure  how to check where my commit message  actually links to.
I tried clicking the commit message I  had sent to see the content but everything seemed okay.

I need help!

**Comment by amjltc295** [comment]
Did you try the two links? See https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/ and https://www.git-tower.com/learn/git/faq/change-author-name-email to fix it.
1. Do you have an email address in your commit message?
2. Is the email in your GitHub account?
3. Did you push your commits to your forked repo?
