### ISSUE TITLE
助教,為何我繳交了但卻沒有分數。

### ISSUE THREAD

**Issue by wongchiseng** [amjltc295/PythonHomework#171]
我前天就己經交了,而且也通過了,他顯示是綠色勾。
但是助教卻回覆我過了期限。
而且今天看是沒分數。
為甚麼會這樣。@amjltc295

**Comment by wongchiseng** [comment]
因為我標題改在字目錄裡面了。以為標題會自動更新。
所以我現在把他title改一改就可以了嗎?謝謉。

**Comment by amjltc295** [comment]
The is no such a thing called 字目錄. They are commit messages and should record what you have done to the code.
Please reopen the PR, and you would not get the 20% PR score.

**Comment by wongchiseng** [comment]
明白,謝謝助教。
