### ISSUE TITLE
Quesion for task 6

### ISSUE THREAD

**Issue by edisonhello** [amjltc295/PythonHomework#22]
Can someone explain why cosine similarity of two identical vector is 0.9999999?
I got 1, then got a WA on all testcases with error < 1e-9.

**Comment by s950449** [comment]
How do you answer it?

**Comment by amjltc295** [comment]
The error is from the precision of float. Did you call dot_product() and norm()?

**Comment by s950449** [comment]
(A dot B)/(norm(A)*norm(B)) and (A dot B)/norm(A)/norm(B) have different answers

I think it is why you got WA

**Comment by edisonhello** [comment]
I got the reason, you're right.
But the more accuracy answer should not be WA since 1 should be the cosine similarity of two identical vector instead of 0.9999999.

**Comment by amjltc295** [comment]
Good point.  We'll handle this in  #54

**Comment by amjltc295** [comment]
Fixed in #54

**Comment by amjltc295** [comment]
@edisonhello please mention this issue when you submit your homework. This worths 30 points.
