### ISSUE TITLE
Fix the frontend table

### ISSUE THREAD

**Issue by amjltc295** [amjltc295/PythonHomework#56]
For our current [website](https://pythonhomework.netlify.com/), the table is fake and the real data is the nested dictionary under the table. If someone could fix it with decent ReactJS before TAs fix it, he/she could get 30 bonus points.

**Comment by ntubiolin** [comment]
In the JSON that is to be rendered:
'
Results: {"results":{"sample_code":{"flake8":0,"import":"Failed"},"sample_task1":{"flake8":7,"import":"Success","private_scores":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0},"public_scores":{"1":4,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0}}},"student_num":2,"task_num":8}, 
'
should we render `"sample_code":{"flake8":0,"import":"Failed"}` as well, or can we just ignore data of this kind?

**Comment by amjltc295** [comment]
Fixed by #79
