### ISSUE TITLE
[Survey] TA hours

### ISSUE THREAD

**Issue by amjltc295** [amjltc295/PythonHomework#58]
I would have one or two timeslots for extra TA hours. As I do not know the schedule of freshmen, please leave your available time here if you need some help.

Options are : 
11/30 Fri 9:00-12:00
11/30 Fri 18:30 - 21:30
12/3 Mon 18:30 - 21:30
12/4 Tue 9:00-12:00
12/5 Wed 18:30 - 21:30
12/7 Fri 9:00-12:00

Probably at R101.

There would be no extra TA hours if there aren't many people.

**Comment by ZG926** [comment]
11/30 Fri 18:30 - 21:30
12/3 Mon 18:30 - 21:30
12/5 Wed 18:30 - 21:30

**Comment by B07902097** [comment]
12/3 Mon 18:30 - 21:30
12/4 Tue 9:00-12:00

**Comment by wildrook29535** [comment]
11/30 Fri 18:30 - 21:30
12/3 Mon 18:30 - 21:30
12/5 Wed 18:30 - 21:30

**Comment by DennyKuo0809** [comment]
12/3 Mon 18:30 - 21:30
12/4 Tue 9:00-12:00
12/5 Wed 18:30 - 21:30

**Comment by payton055** [comment]
11/30 Fri 18:30 - 21:30
12/4 Tue 9:00-12:00
12/5 Wed 18:30 - 21:30

**Comment by ZHsuan** [comment]
12/3 Mon 18:30 - 21:30
12/4 Tue 9:00-12:00
12/7 Fri 9:00-12:00

**Comment by grcsilia** [comment]
11/30 Fri 18:30 - 21:30

**Comment by autumn0409** [comment]
11/30 Fri 9:00-12:00
11/30 Fri 18:30 - 21:30
12/3 Mon 18:30 - 21:30
12/5 Wed 18:30 - 21:30
12/7 Fri 9:00-12:00

**Comment by bbshangs** [comment]
11/30 Fri 18:30 - 21:30
12/3 Mon 18:30 - 21:30
12/5 Wed 18:30 - 21:30

**Comment by amjltc295** [comment]
We will have extra TA hours during
11/30 Fri 18:30 - 21:30
12/3 Mon 18:30 - 21:30
