### ISSUE TITLE
permission?

### ISSUE THREAD

**Issue by DennyKuo0809** [amjltc295/PythonHomework#67]
I saw these error messages on my terminal :

remote: Permission to amjltc295/PythonHomework.git denied to DennyKuo0809. 
fatal: unable to access 'https://github.com/amjltc295/PythonHomework.git/': The requested URL returned error: 403  

@amjltc295 Excuse me. I don't know what happened , and how can I fix it?

**Comment by edisonhello** [comment]
You should fork this repo, and push your commit to your forked repo.

**Comment by edisonhello** [comment]
If you want the send a PR, press 'New pull request' in your own repo.
If you want to push a new commit, make sure that you are pushing into your own repo instead of this.

**Comment by amjltc295** [comment]
@DennyKuo0809  You were pushing commits to this repository, which is prohibited. 
I guess you did something like 
`git push origin master`
Please make sure your `origin` is your forked repository, not this one.
You could check that by `git remote get-url origin`

To set another remote that is your forked url, use
`git remote add forked <your forked URL>`
If `forked` already exists, try `git remote set-url forked <your forked URL>`

Once the URL is set, try
`git push forked master` to push commits to your forked repo
