### ISSUE TITLE
Create Account Using NTU Mail But Can't Create a Private Repo

### ISSUE THREAD

**Issue by b07902123** [amjltc295/PythonHomework#7]
Hello everyone.
In the part "Please create a GitHub account", it is said that if you create an account using NTU mail, you would be entitled to start a private repository. However, after creating the account by using NTU mail, it seems that I still need to pay something to create a private repo.
Does anyone successfully create a private repo? Or can anyone tell me what's wrong? Thanks.

---
![image](https://user-images.githubusercontent.com/45309271/48967162-65584d80-f017-11e8-993a-5390f6e858af.png)
---

**Comment by amjltc295** [comment]
You need to apply for the [Student Developer Pack](https://education.github.com/pack), and it takes about five days. However, it should ask if you are a student when registering and redirect you to the GitHub Education page. Did you skip the process?

**Comment by amjltc295** [comment]
By the way, for this homework, you need not a private repo.

**Comment by b07902123** [comment]
Thanks for your replying! I will try it.
