### ISSUE TITLE
Commonly used Git operations

### ISSUE THREAD

**Issue by amjltc295** [amjltc295/PythonHomework#71]
As this repository is frequently updated, students need to update their local&forked repo as well. 
If someone could make a clear tutorial for this (or other git operations), he/she could get up to 30 points.
`git rebase` is preferred.

**Comment by amjltc295** [comment]
Partially fixed by #82 . @edisonhello Please mention this issue when you submit your homework. This worths 10 points.

**Comment by amjltc295** [comment]
Fixed by #78 . @s950449 Please mention this issue when you submit your homework. This worths 20 points.

**Comment by s950449** [comment]
There are some typo in FAQ

**Comment by s950449** [comment]
I will make a PR to solve
