### ISSUE TITLE
Can't pass Netlify test

### ISSUE THREAD

**Issue by robert1003** [amjltc295/PythonHomework#75]
What are those tests testing?
I tried but I couldn't figure out what are the standards.

**Comment by amjltc295** [comment]
There is no test for Netlify. It simply deploys the frontend. 
Many people face this issue, and I'm still trying to reproduce it.
Did you update your repo to the lastest?

**Comment by robert1003** [comment]
Yes I do

**Comment by amjltc295** [comment]
Ok, I found the problem. You probably sent a PR with an older version, where a React package is not included. Netlify will kind of cache installed packages and skip the installing process to save time. However, if a new package is required, we need to clean the cache and deploy again. It should be fine now.

**Comment by robert1003** [comment]
Thanks a lot.
