### ISSUE TITLE
built failed

### ISSUE THREAD

**Issue by DennyKuo0809** [amjltc295/PythonHomework#86]
Why my push requests was incorrect (X)?  It said built fail. Please tell me why?

**Comment by DennyKuo0809** [comment]
@amjltc295

**Comment by amjltc295** [comment]
See #75

**Comment by amjltc295** [comment]
@DennyKuo0809 Sorry, your error is different from #75. See https://travis-ci.com/amjltc295/PythonHomework/builds/92806137 for details.
